module.exports = {
  STATUS_FLOW_MAPPER: {
    SUBMITTED: ["PRINTED", "DISCARDED"],
    PRINTED: ["RECEIVED", "REPRINT", "DISCARDED"],
    RECEIVED: ["DELIVERED", "DISCARDED"],
    DELIVERED: ["DISCARDED"],
    DISCARDED: ["DELIVERED", "REPRINT", "SUBMITTED"],
  },
};
