module.exports = {
  STATUS_FLOW_MAPPER: {
    SUBMITTED: ["PRINTED", "DISCARDED"],
    PRINTED: ["RECEIVED", "REPRINT", "DISCARDED"],
    RECEIVED: ["DELIVERED", "DISCARDED"],
    DELIVERED: ["DISCARDED"],
    PENDING: ["SUBMITTED", "DISCARDED"],
    DISCARDED: ["DELIVERED", "REPRINT", "SUBMITTED", "PENDING"],
    UNDELIVERED: ["DELIVERED", "REPRINT", "SUBMITTED"],
  },
  ROLES_ALLOWED_TO_UPDATE_STATUS: {
    TL: ["SUBMITTED", "PRINTED", "DISCARDED", "OFD", "RTO", "DELIVERED"],
    FE: ["RECEIVED", "OFD", "DELIVERED", "RTO"],
    ADMIN: [
      "SUBMITTED",
      "PRINTED",
      "REPRINT",
      "RECEIVED",
      "OFD",
      "DELIVERED",
      "RTO",
      "PENDING",
      "DISCARDED",
      "UNDELIVERED",
    ],
  },
  CARD_TYPE: {
    Single: "Single",
    Family: "Family",
  },
};
