module.exports = {
  areaSchema: require("./area"),
  binSchema: require("./bin"),
  cardSchema: require("./card"),
  configSchema: require("./config"),
  dashboardDataSchema: require("./dashboard_data"),
  districtSchema: require("./district"),
  gramSchema: require("./gram"),
  hospitalSchema: require("./hospital"),
  newTehsilSchema: require("./new_tehsil"),
  otpSchema: require("./otp"),
  permissionsSchema: require("./permissions"),
  rolesSchema: require("./roles"),
  servicesSchema: require("./services"),
  settingSchema: require("./setting"),
  statesSchema: require("./states"),
  tehsilSchema: require("./tehsil"),
  tokenSchema: require("./token"),
  userSchema: require("./user"),
  newTehsilSchema: require("./new_tehsil"),
  // Payment Modelss
  orderSchema: require("./orders"),
  transactionSchema: require("./transactions"),
  walletSchema: require("./wallet"),
  planSchema: require("./plans"),
  purchasedPlanSchema: require("./purchasedPlans"),
  pincode: require("./pincode"),
  faqs: require("./FAQs"),
};
